environment {
        DOCKERHUB_CREDENTIALS = credentials('fercz-docker-registry')
        DOCKER_IMAGE = 'fercz/pois-api:v1.4'
}

   stage('Build') {
          steps {
            sh 'sudo docker build -t ${DOCKER_IMAGE} .'
          }
        }
        stage('Login & Push') {
          steps {
                sh '''
                    echo $DOCKERHUB_CREDENTIALS_PSW | sudo docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin docker.io
                    sudo docker push ${DOCKER_IMAGE}
                '''
          }
        }
